apply {
    plugin "com.android.library"
    plugin "kotlin-android"
    plugin "kotlin-android-extensions"
}

android {
    compileSdkVersion sdk
    defaultConfig {
        minSdkVersion minSdk
        versionCode 1
        versionName "1.30.6"
        consumerProguardFiles 'proguard-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.code.gson:gson:2.8.5'

    implementation "com.android.support:appcompat-v7:${support_version}"
    implementation "com.android.support:design:${support_version}"

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.robolectric:robolectric:4.3.1'
    testImplementation 'com.google.code.gson:gson:2.8.5'
    testImplementation "com.android.support:appcompat-v7:${support_version}"
    testImplementation "com.android.support:design:${support_version}"
    testImplementation 'org.greenrobot:eventbus:3.1.1'
}

//apply from: "${rootDir.path}/gradle/publish.gradle"
//publish {
//    name = "UtilCode"
//    groupId = Config.depConfig.lib_utilcode.groupId
//    artifactId = Config.depConfig.lib_utilcode.artifactId
//    version = Config.depConfig.lib_utilcode.version
//    website = "https://github.com/Blankj/AndroidUtilCode"
//}